config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :storages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  after_create_commit { broadcast_prepend_to 'products' }
  after_update_commit { broadcast_replace_to 'products' }
  after_destroy_commit { broadcast_remove_to 'products' }

  validates :name, uniqueness: true, presence: true
  validates :stock, numericality: { only_integer: true }, presence: true
  validates :description, presence: true
end

app/models/storage.rb
class Storage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @product = Product.new
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.turbo_stream { }
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@product, partial: "products/form", locals: { product: @product}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.turbo_stream # add format turbo_stream
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        # format.turbo_stream # add format turbo_stream
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@product, partial: "products/form", locals: { product: @product}) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :stock)
    end
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :set_storage, only: %i[ show edit update destroy ]

  # GET /storages or /storages.json
  def index
    @storages = Storage.all
  end

  # GET /storages/1 or /storages/1.json
  def show
  end

  # GET /storages/new
  def new
    @storage = Storage.new
  end

  # GET /storages/1/edit
  def edit
  end

  # POST /storages or /storages.json
  def create
    @storage = Storage.new(storage_params)

    respond_to do |format|
      if @storage.save
        format.html { redirect_to storage_url(@storage), notice: "Storage was successfully created." }
        format.json { render :show, status: :created, location: @storage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1 or /storages/1.json
  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html { redirect_to storage_url(@storage), notice: "Storage was successfully updated." }
        format.json { render :show, status: :ok, location: @storage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1 or /storages/1.json
  def destroy
    @storage.destroy

    respond_to do |format|
      format.html { redirect_to storages_url, notice: "Storage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storage
      @storage = Storage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def storage_params
      params.require(:storage).permit(:name, :manager, :address, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TuBodegita</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= turbo_include_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.slim
= form_with(model: product, id: dom_id(product)) do |f|
  - if product.errors.any?
    #error_explanation
      h2 = "#{pluralize(product.errors.count, 'error')} prohibited this product from being saved:"
      ul
        - product.errors.full_messages.each do |message|
          li = message
          li = product.errors.messages


  .mb-3.row
    = f.label 'Nombre', class: 'col-sm-2 col-form-label'
    .col-sm-8
      = f.text_field :name, class: 'form-control'
  .mb-3.row
    = f.label 'Descripción', class: 'col-sm-2 col-form-label'
    .col-sm-8
      = f.text_field :description, class: 'form-control'
  .mb-3.row
    = f.label 'Cantidad', class: 'col-sm-2 col-form-label'
    .col-sm-8
      = f.number_field :stock, class: 'form-control'
  .mb-3.row
    .actions 
      = f.submit 'Enviar', class: 'btn btn-primary'

app/views/products/_form_edit.html.slim
= form_with(model: product, id: dom_id(product)) do |f|
  - if product.errors.any?
    #error_explanation
      h2 = "#{pluralize(product.errors.count, 'error')} prohibited this product from being saved:"
      ul
        - product.errors.full_messages.each do |message|
          li = message


  .mb-3.row
    = f.label 'Nombre', class: 'col-sm-4 col-form-label'
    .col-sm-8
      = f.text_field :name, class: 'form-control'
  .mb-3.row
    = f.label 'Descripción', class: 'col-sm-4 col-form-label'
    .col-sm-8
      = f.text_field :description, class: 'form-control'
  .mb-3.row
    = f.label 'Cantidad', class: 'col-sm-4 col-form-label'
    .col-sm-8
      = f.number_field :stock, class: 'form-control'
  .mb-3.row
    .actions 
      = f.submit 'Enviar', class: 'btn btn-primary'
      = link_to 'Cancelar', products_path, class: 'btn btn-outline-secondary mx-1'

app/views/products/_product.html.slim
= turbo_frame_tag dom_id(product) do

  .card.card-body
    .row
      .col-8
        .row
          .col
            .fs-1 = product.name
          .col
            - color = 'text-danger' if product.stock.between?(-9999999999, 3)
            - color = 'text-warning' if product.stock.between?(3, 10)
            - color = 'text-success' if product.stock > 10
            - if product.stock == 1
              span.align-middle[class=color] = "#{product.stock} producto disponible"
            - else
              span.align-middle[class=color] = "#{product.stock} productos disponibles"
        .row
          .col
            p = product.description
      .col-4.d-grid.gap-2.d-md-flex.justify-content-md-end
        mt-2
          = link_to "Editar", edit_product_path(product), class: 'btn btn-warning mx-1', data: { 'turbo-frame': 'edit_product' }
          = turbo_frame_tag :edit_product
          = link_to "Borrar", product, data: { confirm: 'Are you sure?', turbo_method: 'delete' }, class: 'btn btn-outline-secondary mx-1'

app/views/products/edit.html.slim
= turbo_frame_tag :edit_product do
  .card
    .card-body
      == render 'form_edit', product: @product

app/views/products/index.html.slim
p id="notice" = notice

h1 Productos

= turbo_stream_from 'products'

.card.p-3.mb-5.rounded.shadow.bg-body
  .card-body
    = turbo_frame_tag 'product_form' do
      = render 'products/form', product: @product

h2 Listado
= turbo_frame_tag 'products' do
  = render @products

app/views/products/new.html.slim
h1 New product

== render 'form'

= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name

p
  strong Description:
  = @product.description

p
  strong Stock:
  = @product.stock

=> link_to 'Edit', edit_product_path(@product)
'|
=< link_to 'Back', products_path

app/views/storages/_form.html.slim
= form_for @storage do |f|
  - if @storage.errors.any?
    #error_explanation
      h2 = "#{pluralize(@storage.errors.count, 'error')} prohibited this storage from being saved:"
      ul
        - @storage.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :manager
    = f.text_field :manager
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :description
    = f.text_field :description
  .actions = f.submit

app/views/storages/edit.html.slim
h1 Editing storage

== render 'form'

=> link_to 'Show', @storage
'|
=< link_to 'Back', storages_path

app/views/storages/index.html.slim
h1 Listing storages

table
  thead
    tr
      th Name
      th Manager
      th Address
      th Description
      th
      th
      th

  tbody
    - @storages.each do |storage|
      tr
        td = storage.name
        td = storage.manager
        td = storage.address
        td = storage.description
        td = link_to 'Show', storage
        td = link_to 'Edit', edit_storage_path(storage)
        td = link_to 'Destroy', storage, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Storage', new_storage_path

app/views/storages/new.html.slim
h1 New storage

== render 'form'

= link_to 'Back', storages_path

app/views/storages/show.html.slim
p#notice = notice

p
  strong Name:
  = @storage.name

p
  strong Manager:
  = @storage.manager

p
  strong Address:
  = @storage.address

p
  strong Description:
  = @storage.description

=> link_to 'Edit', edit_storage_path(@storage)
'|
=< link_to 'Back', storages_path